name: phd-thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.18.1
  - pandas=1.0.3
  - matplotlib=3.2.1
  - seaborn=0.10.1
  - jupyterlab=2.1.2
  - root=6.20.4
  - root_numpy=4.8.0
  - root_pandas=0.7.0
  - flake8=3.7.9
  - autopep8=1.5.2
  - tqdm=4.45.0
  - mplhep=0.1.20
  - pip=20.0.2
  - pip:
    - PyLaTeX=1.3.1