name: phd-thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.1.5
  - matplotlib=3.3.3
  - jupyterlab=2.2.9
  - tqdm=4.54.1
  - mplhep=0.2.9
  - uproot=3.13.0