name: build and publish
on: push
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -f
      - name: publish
        run: |
          mv thesis.pdf thesis_new.pdf
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout gh-pages
          mv thesis_new.pdf thesis.pdf
          git add thesis.pdf
          git commit -m "new thesis version"
          git push origin gh-pages